FROM nginx:alpine

# 기존 페이지 삭제
RUN rm -rf /usr/share/nginx/html/*

# [보완] 빌드 시점에 영향을 주지 않는 더미 인자를 추가하여 캐시를 방지할 수 있습니다.
# 하지만 보통은 아래 COPY 문만 정확하면 됩니다.
COPY mouse_log_test.html /usr/share/nginx/html/index.html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
