FROM python:3.9-slim

# PostgreSQL 접속을 위한 라이브러리 의존성 설치
RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*
# 의존성 패키지 설치 (flask-cors 포함)
RUN pip install flask flask-cors psycopg2-binary

WORKDIR /app

# [핵심 수정] app.py만 복사하는 대신, 현재 디렉토리의 모든 파일과 폴더를 복사합니다.
COPY . .

EXPOSE 5000
CMD ["python", "app.py"]
