apiVersion: apps/v1
kind: Deployment
metadata:
  name: mouse-back-deploy
spec:
  replicas: 2 # 워커 노드 2개에 각각 하나씩 배포
  selector:
    matchLabels:
      app: mouse-back
  template:
    metadata:
      labels:
        app: mouse-back
    spec:
      containers:
      - name: mouse-back
        image: ${{ secrets.DOCKER_USER }}/mouse-back:latest
        ports:
        - containerPort: 5000 # app.py가 사용하는 포트
        env:
        - name: DB_HOST
          value: "10.0.x.x" # 여기에 DB VM의 Private IP를 넣으세요
---
apiVersion: v1
kind: Service
metadata:
  name: mouse-back-service
spec:
  selector:
    app: mouse-back
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
