apiVersion: apps/v1
kind: Deployment
metadata:
  name: mouse-back-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mouse-back
  template:
    metadata:
      labels:
        app: mouse-back
    spec:
      containers:
      - name: mouse-back
        # <DOCKER_ID>를 실제 본인의 도커 허브 아이디로 직접 수정하세요.
        image: <DOCKER_ID>/mouse-back:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mouse-back-service
spec:
  type: ClusterIP
  selector:
    app: mouse-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
