apiVersion: apps/v1
kind: Deployment
metadata:
  name: agami-backend
  namespace: agami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agami-backend
  template:
    metadata:
      labels:
        app: agami-backend
    spec:
      nodeSelector:
        zone: backend
      containers:
      - name: backend
        image: agami-captcha.cloud:8443/agami/backend:2606101112
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "postgres-db-postgresql.default.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "admin1234"
        - name: DB_NAME
          value: "agamidb"
        - name: KAKAO_CLIENT_ID
          value: "21bb77241dca5e660b3bdc037ed54db3"
        - name: KAKAO_REDIRECT_URI
          value: "https://agami-captcha.cloud/auth/kakao/callback"
        - name: JWT_SECRET_KEY
          value: "super-secret-key-for-agami-jwt-token"
        - name: JWT_ALGORITHM
          value: "HS256"
        - name: JWT_EXPIRE_MINUTES
          value: "60"
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/letsencrypt/live/agami-captcha.cloud
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: agami-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: agami-backend-svc
  namespace: agami
spec:
  selector:
    app: agami-backend
  ports:
    - port: 80
      targetPort: 8000