apiVersion: apps/v1
kind: Deployment
metadata:
  name: agami-backend
  namespace: agami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agami-backend
  template:
    metadata:
      labels:
        app: agami-backend
    spec:
      nodeSelector:
        zone: backend
      containers:
      - name: backend
        image: agami-captcha.cloud:8443/agami/backend:2606241616
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        # 환경 변수를 Secret에서 주입하도록 수정
        env:
        - name: DB_HOST
          value: "postgres-db-postgresql.default.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "admin"
        - name: DB_NAME
          value: "agamidb"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: agami-env-secret
              key: DB_PASSWORD
        - name: KAKAO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: agami-env-secret
              key: KAKAO_CLIENT_ID
        - name: KAKAO_REDIRECT_URI
          value: "https://agami-captcha.cloud/auth/kakao/callback"
        - name: KAKAO_PAY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: agami-env-secret
              key: KAKAO_PAY_SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: agami-env-secret
              key: JWT_SECRET_KEY
        - name: JWT_ALGORITHM
          value: "HS256"
        - name: JWT_EXPIRE_MINUTES
          value: "60"
        - name: CAPTCHA_DB_URL
          valueFrom:
            secretKeyRef:
              name: captcha-app-secret
              key: CAPTCHA_DB_URL_SYNC
        - name: API_KEY_HMAC_PEPPER
          valueFrom:
            secretKeyRef:
              name: captcha-app-secret
              key: API_KEY_HMAC_PEPPER
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/letsencrypt/live/agami-captcha.cloud
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: agami-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: agami-backend-svc
  namespace: agami
spec:
  selector:
    app: agami-backend
  ports:
    - port: 80
      targetPort: 8000