apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agami-ingress
  namespace: agami
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - agami-captcha.cloud
    secretName: agami-web-tls
  rules:
  - host: agami-captcha.cloud
    http:
      paths:
      - path: /widget
        pathType: Prefix
        backend:
          service:
            name: captcha-api
            port:
              number: 80
      - path: /captcha
        pathType: Prefix
        backend:
          service:
            name: captcha-api
            port:
              number: 80
      - path: /static/captcha_images
        pathType: Prefix
        backend:
          service:
            name: captcha-api
            port:
              number: 80
      # 팀원분 코드에 추가된 라벨 경로
      - path: /captcha_labels
        pathType: Prefix
        backend:
          service:
            name: captcha-api
            port:
              number: 80
      # 질문자님의 프론트엔드 경로
      - path: /
        pathType: Prefix
        backend:
          service:
            name: agami-frontend-svc
            port:
              number: 80