apiVersion: apps/v1
kind: Deployment
metadata:
  name: agami-frontend
  namespace: agami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agami-frontend
  template:
    metadata:
      labels:
        app: agami-frontend
    spec:
      nodeSelector:
        zone: frontend
      containers:
      - name: frontend
        image: agami-captcha.cloud:8443/agami/frontend:2607011906
        resources:
          requests:
            cpu: "500m"      # 스케줄러는 0.5코어만 비어있으면 파드를 배치함 (Pending 해결!)
            memory: "512Mi"
          limits:
            cpu: "2000m"     # 실제 동작 시 최대 2코어까지 풀로 사용 가능
            memory: "2Gi"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: agami-frontend-svc
  namespace: agami
spec:
  selector:
    app: agami-frontend
  ports:
    - port: 80
      targetPort: 80