apiVersion: apps/v1
kind: Deployment
metadata:
  name: agami-frontend
  namespace: agami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agami-frontend
  template:
    metadata:
      labels:
        app: agami-frontend
    spec:
      nodeSelector:
        zone: frontend
      containers:
      - name: frontend
        image: agami-captcha.cloud:8443/agami/frontend:2606191034 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: agami-frontend-svc
  namespace: agami
spec:
  selector:
    app: agami-frontend
  ports:
    - port: 80
      targetPort: 80