name: Deploy to Bastion Minikube

on:
  push:
    branches: [ "main" ] # 메인 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Kubernetes Context
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_DATA }}

    - name: Deploy Backend to Minikube
      run: |
        # 이미지에 명시된 k8s 경로의 설정 파일들을 적용합니다.
        kubectl apply -f k8s/backend-deploy.yml
        
    - name: Verify Deployment
      run: |
        kubectl get pods -n default
        kubectl get svc -n default
