name: Deploy to Bastion Minikube

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_DATA }}

      - name: Deploy Backend to Minikube
        run: |
          # 이미지 내 k8s 폴더의 경로를 참조합니다.
          kubectl apply -f k8s/backend-deploy.yml
        
      - name: Verify Deployment
        run: |
          kubectl get pods -n default
          kubectl get svc -n default
