name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Develop/Frontend/**'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. HTTP 허용 설정 (Insecure Registry)
      - name: Set up Docker to allow HTTP
        run: |
          if [ ! -f /etc/docker/daemon.json ]; then echo "{}" | sudo tee /etc/docker/daemon.json; fi
          sudo jq '. + {"insecure-registries": ["${{ secrets.HARBOR_URL }}"]}' /etc/docker/daemon.json > /tmp/daemon.json
          sudo mv /tmp/daemon.json /etc/docker/daemon.json
          sudo systemctl restart docker

      # 2. 직접 쉘 명령어로 로그인 (Error: http: server... 에러 방지)
      - name: Shell Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ secrets.HARBOR_URL }} -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      # 3. 이미지 빌드 및 푸시
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./Develop/Frontend
          file: ./Develop/Frontend/Dockerfile
          push: true
          # library를 agami로 수정 완료
          tags: ${{ secrets.HARBOR_URL }}/agami/frontend:latest
