name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Develop/Frontend/**' # Frontend 폴더 변경 시에만 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./Develop/Frontend
          file: ./Develop/Frontend/Dockerfile
          push: true
          tags: ${{ secrets.HARBOR_URL }}/library/frontend:latest
